# -*- coding: utf-8 -*-
"""cog-1 encoder (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QDqE2TBI-NyA-D17six35HYJe4l2R4iB
"""

import pandas as pd
import numpy as np
df_pyarrow = pd.read_parquet('cog.parquet', engine='pyarrow')
print(df_pyarrow['EVENT_ID'].head())
print(df_pyarrow['EVENT_ID'].isnull().sum())

# List of columns to keep
keep_cols = [
     'PATNO', 'EVENT_ID','DIFFNEWS', 'DIFFTIME', 'DIFFMONEY', 'DIFFINST', 'DIFFPROBLEM', 'DIFFSTEPS',
    'DIFFERRAND', 'DIFFMAP', 'DIFFINFO', 'DIFFMORE', 'DIFFGADGET', 'DIFFAFFAIRS',
    'DIFFTHOUGHT', 'DIFFDISC', 'DIFFREM', 'DIFFCONS', 'DIFFTOPIC', 'DIFFWORD',
    'DIFFORG', 'DIFFTASK', 'DIFFSWITCH', 'DIFFAPPT', 'DIFFRECALL', 'DIFFRECENT',
    'DIFFKEPT', 'DIFFNAME', 'DIFFFAMILIAR','visit_phase'
]

# Keep only these columns in the DataFrame
df_pyarrow = df_pyarrow[keep_cols]

import pandas as pd

# Convert symptom columns to numeric
symptom_cols = [col for col in df_pyarrow.columns if col not in ['PATNO', 'visit_phase']]
for col in symptom_cols:
    df_pyarrow[col] = pd.to_numeric(df_pyarrow[col], errors='coerce')

# Group and calculate mean prevalence by 'stage'
prevalence = (
    df_pyarrow.groupby('visit_phase')[symptom_cols]
    .mean()
    .transpose()
)

# prevalence will be a DataFrame: rows = symptoms, columns = stages; values = mean presence (proportion)
print("Symptom prevalence by stage:")
print(prevalence)

# To identify symptoms with notable stage-specific variation
# e.g., difference from early to late
prevalence['diff_late_early'] = prevalence['late'] - prevalence['early']
prevalence['max_diff'] = prevalence.max(axis=1) - prevalence.min(axis=1)

# Sort symptoms by largest change across stages
notable_symptoms = prevalence.sort_values(by='max_diff', ascending=False)

print("Symptoms sorted by greatest change across stages:")
print(notable_symptoms)

# If needed, drop or ignore non-symptom rows
symptom_rows = [ix for ix in prevalence.index if ix not in ['EVENT_ID', 'COGCAT_TEXT']]
prevalence_symptoms = prevalence.loc[symptom_rows, ['early', 'mid', 'late']]

# Find top 2 symptoms for each stage
top_symptoms_per_stage = {}
for stage in ['early', 'mid', 'late']:
    top_symptoms = prevalence_symptoms[stage].nlargest(3).index.tolist()
    top_symptoms_per_stage[stage] = top_symptoms

print("Top 3 symptoms by stage:", top_symptoms_per_stage)

# Convert to str for grouping
selected_symptoms = list(set(sum(top_symptoms_per_stage.values(), [])))
print("Unique top symptoms overall:", selected_symptoms)

# Use only these for encoder input preparation
df_pyarrow['PATNO'] = df_pyarrow['PATNO'].astype(str)
df_pyarrow['visit_phase'] = df_pyarrow['visit_phase'].astype(str)

df_pyarrowagg = df_pyarrow.groupby(['PATNO', 'visit_phase'])[selected_symptoms].mean().reset_index()

pivoted = {
    symptom: df_pyarrowagg.pivot(index='PATNO', columns='visit_phase', values=symptom).fillna(0)
    for symptom in selected_symptoms
}

arrays = [pivoted[s].to_numpy() for s in selected_symptoms]
autoencoder_input_cog= np.stack(arrays, axis=2)

print(autoencoder_input_cog.shape)
df_pyarrow['PATNO'] = df_pyarrow['PATNO'].astype(str)
df_pyarrow['visit_phase'] = df_pyarrow['visit_phase'].astype(str)

# Aggregate by patient and visit_phase
df_pyarrowagg = df_pyarrow.groupby(['PATNO', 'visit_phase'])[selected_symptoms].mean().reset_index()

# Pivot each symptom with visit_phase as columns
pivoted = {
    symptom: df_pyarrowagg.pivot(index='PATNO', columns='visit_phase', values=symptom).fillna(0)
    for symptom in selected_symptoms
}

# Stack into 3D array: patients x stages x symptoms
arrays = [pivoted[s].to_numpy() for s in selected_symptoms]
autoencoder_input_cog = np.stack(arrays, axis=2)


np.save('autoencoder_input_cog1.npy', autoencoder_input_cog)



