# -*- coding: utf-8 -*-
"""master_patient_split (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yEcJQ0RYl6RMZ0lpzdUh-JmVgZDxAUx9
"""

import pickle
import pandas as pd
import numpy as np

print("Loading all datasets to find common patients...")

# Load motor data
df_motor = pd.read_parquet('motor.parquet', engine='pyarrow')
motor_patients = set(df_motor['PATNO'].unique())
print(f"Motor patients: {len(motor_patients)}")

# Load non-motor data
df_cog = pd.read_parquet('cog.parquet', engine='pyarrow')
df_psych = pd.read_parquet('merged_df.parquet', engine='pyarrow')
df_sleep = pd.read_parquet('df2_Selected.parquet', engine='pyarrow')
df_auto = pd.read_parquet('Merged_Df.parquet', engine='pyarrow')
df_sens = pd.read_parquet('sleep.parquet', engine='pyarrow')

nonmotor_patients = set()
for df in [df_cog, df_psych, df_sleep, df_auto, df_sens]:
    nonmotor_patients.update(df['PATNO'].unique())
print(f"Non-motor patients: {len(nonmotor_patients)}")

# Load imaging data
df_dti = pd.read_parquet('dti.parquet', engine='pyarrow')
df_mri = pd.read_parquet('mri.parquet', engine='pyarrow')
imaging_patients = set(df_dti['PATNO'].unique()) | set(df_mri['PATNO'].unique())
print(f"Imaging patients: {len(imaging_patients)}")

# Find patients that appear in ALL modalities (for best results)
all_modality_patients = motor_patients & nonmotor_patients & imaging_patients
print(f"\nPatients in ALL modalities: {len(all_modality_patients)}")

# Or use union if you want to include all patients
all_patients = list(motor_patients | nonmotor_patients | imaging_patients)
print(f"Patients in ANY modality: {len(all_patients)}")

# Choose which set to use (recommend using union)
patients_to_split = all_patients

# Shuffle and split (70% train, 15% val, 15% test)
np.random.seed(42)
np.random.shuffle(patients_to_split)

n = len(patients_to_split)
train_size = int(0.7 * n)
val_size = int(0.15 * n)

train_patients = patients_to_split[:train_size]
val_patients = patients_to_split[train_size:train_size+val_size]
test_patients = patients_to_split[train_size+val_size:]

# Verify no overlap
assert len(set(train_patients) & set(val_patients)) == 0, "Train/Val overlap!"
assert len(set(train_patients) & set(test_patients)) == 0, "Train/Test overlap!"
assert len(set(val_patients) & set(test_patients)) == 0, "Val/Test overlap!"

print(f"\nNew split created:")
print(f"  Train: {len(train_patients)} patients ({100*len(train_patients)/n:.1f}%)")
print(f"  Val:   {len(val_patients)} patients ({100*len(val_patients)/n:.1f}%)")
print(f"  Test:  {len(test_patients)} patients ({100*len(test_patients)/n:.1f}%)")

# Check coverage per modality
print(f"\nCoverage per modality:")
print(f"  Motor - Train: {len(set(train_patients) & motor_patients)}, Val: {len(set(val_patients) & motor_patients)}, Test: {len(set(test_patients) & motor_patients)}")
print(f"  Non-motor - Train: {len(set(train_patients) & nonmotor_patients)}, Val: {len(set(val_patients) & nonmotor_patients)}, Test: {len(set(test_patients) & nonmotor_patients)}")
print(f"  Imaging - Train: {len(set(train_patients) & imaging_patients)}, Val: {len(set(val_patients) & imaging_patients)}, Test: {len(set(test_patients) & imaging_patients)}")

# Save to pickle
split_data = {
    'train_patients': train_patients,
    'val_patients': val_patients,
    'test_patients': test_patients
}

with open('master_patient_split.pkl', 'wb') as f:
    pickle.dump(split_data, f)

print("\n✓ Saved to 'master_patient_split.pkl'")
print("✓ No patient leakage - safe to use!")

