# -*- coding: utf-8 -*-
"""Motor progression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jM6a0jcro0SCkVqTq8D8SGSq0drk-TPR
"""

import pandas as pd
import numpy as np

df1=pd.read_csv(r"C:\Users\harsh\Downloads\Participant_Motor_Function_Questionnaire_11Nov2025.csv")

cols_to_drop = ['PAG_NAME', 'INFODT', 'CMPLBY2','ORIG_ENTRY','LAST_UPDATE']
df1 = df1.drop(cols_to_drop, axis=1)

new_csv_files = [
    r"C:\Users\harsh\Downloads\Neuro_QoL__Upper_Extremity_Function_-_Short_Form_11Nov2025.csv",
    r"C:\Users\harsh\Downloads\Neuro_QoL__Lower_Extremity_Function__Mobility__-_Short_Form_11Nov2025.csv",
    r"C:\Users\harsh\Downloads\MDS-UPDRS_Part_I_11Nov2025.csv",
    r"C:\Users\harsh\Downloads\MDS-UPDRS_Part_I_Patient_Questionnaire_11Nov2025.csv",
    r"C:\Users\harsh\Downloads\MDS_UPDRS_Part_II__Patient_Questionnaire_11Nov2025.csv"
]
  # or add 'file5.csv'

for fname in new_csv_files:
    temp_df = pd.read_csv(fname)
    df1 = pd.merge(df1, temp_df, on=['PATNO', 'EVENT_ID'], how='outer', suffixes=('', '_dup'))

print(list(df1.columns))

columns_to_keep = ['PATNO', 'EVENT_ID', 'TRBUPCHR', 'WRTSMLR', 'VOICSFTR', 'POORBAL', 'FTSTUCK', 'LSSXPRSS', 'ARMLGSHK', 'TRBBUTTN', 'SHUFFLE', 'MVSLOW','NP2SPCH', 'NP2SALV', 'NP2SWAL', 'NP2EAT', 'NP2DRES', 'NP2HYGN',
                   'NP2HWRT', 'NP2HOBB', 'NP2TURN', 'NP2TRMR', 'NP2RISE', 'NP2WALK', 'NP2FREZ','NQUEX29', 'NQUEX20', 'NQUEX44', 'NQUEX36', 'NQUEX30',
                   'NQUEX28', 'NQUEX33', 'NQUEX37','NQMOB37', 'NQMOB30', 'NQMOB26', 'NQMOB32', 'NQMOB25', 'NQMOB33', 'NQMOB31', 'NQMOB28']
df1 = df1[columns_to_keep]

print(list(df1.columns))

df1.head(100)

threshold = len(df1) * 0.5
df1.dropna(thresh=threshold, axis=1, inplace=True)

df1.head()

import pandas as pd
import numpy as np

# ---------- 1. Load and prepare cohort data ----------
df_cohort_full = pd.read_csv(r"C:\Users\harsh\Downloads\Participant_Status_11Nov2025.csv")
print("Cohort columns:", df_cohort_full.columns)

# Replace 'COHORT' below with the actual cohort column name if different
df_cohort = df_cohort_full[['PATNO', 'COHORT']].copy()
print(df_cohort.head())

# Ensure PATNO and COHORT are strings and strip whitespace
df_cohort['PATNO'] = df_cohort['PATNO'].astype(str).str.strip()
df_cohort['COHORT'] = df_cohort['COHORT'].astype(str).str.strip()

# Filter only PD-diagnosed participants (COHORT == '1')
pd_patnos = set(df_cohort[df_cohort['COHORT'] == '1']['PATNO'])
print(f"Number of PD patients: {len(pd_patnos)}")

# ---------- 2. Filter main DataFrame for PD patients ----------
# Assume df1 is your main DataFrame loaded earlier
df1['PATNO'] = df1['PATNO'].astype(str).str.strip()
df1 = df1[df1['PATNO'].isin(pd_patnos)].copy()

# Ensure EVENT_ID is string
df1['EVENT_ID'] = df1['EVENT_ID'].astype(str).str.strip()

# ---------- 3. Compute EVENT_ID–based visit_phase ----------
visit_sequences = df1.groupby('PATNO')['EVENT_ID'].apply(list)
positions = {}
for visits in visit_sequences:
    for pos, eid in enumerate(visits, 1):
        positions.setdefault(eid, []).append(pos)
mean_positions = {eid: sum(lst) / len(lst) for eid, lst in positions.items()}

sorted_eids = sorted(mean_positions, key=mean_positions.get)
n = len(sorted_eids)
visit_categories = {
    eid: 'Early' if i < n // 3 else 'Mid' if i < 2 * n // 3 else 'Late'
    for i, eid in enumerate(sorted_eids)
}
df1['Visit_Phase'] = df1['EVENT_ID'].map(visit_categories)

# ---------- 4. Compute Composite Motor Score and Clinical Stage ----------
motor_cols = [
    'NP2SPCH','NP2SALV','NP2SWAL','NP2EAT','NP2DRES',
    'NP2HYGN','NP2HWRT','NP2HOBB','NP2TURN','NP2TRMR',
    'NP2RISE','NP2WALK','NP2FREZ'
]
df1['Total_Motor_Score'] = df1[motor_cols].sum(axis=1)
df1['Motor_Stage'] = pd.cut(
    df1['Total_Motor_Score'],
    bins=[-1, 12, 29, np.inf],
    labels=['Early', 'Mid', 'Late']
)

# ---------- 5. Combine Visit_Phase and Motor_Stage into a single stage ----------
def align_stage(row):
    order = {'Early': 0, 'Mid': 1, 'Late': 2}
    vp, ms = row['Visit_Phase'], row['Motor_Stage']
    if pd.isna(vp): return ms
    if pd.isna(ms): return vp
    return vp if order[vp] >= order[ms] else ms

df1['Combined_Stage'] = df1.apply(align_stage, axis=1)

# ---------- 6. Review results ----------
print("\nSample staging results:")
print(
    df1[['PATNO', 'EVENT_ID', 'Visit_Phase', 'Total_Motor_Score',
         'Motor_Stage', 'Combined_Stage']]
    .drop_duplicates()
    .head(20)
)

print("\nStage counts:")
print(df1['Combined_Stage'].value_counts())

# ---------- 7. (Optional) Save to CSV ----------
# df1.to_csv(r"E:\pd-data\processed\staged_data.csv", index=False)

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Assume df1 with Combined_Stage already computed, and motor_cols defined

# Melt the DataFrame to long format for plotting
symptom_df = df1.melt(
    id_vars=['PATNO', 'EVENT_ID', 'Combined_Stage'],
    value_vars=motor_cols,
    var_name='Symptom_Code',
    value_name='Severity'
)

# Map codes to descriptive names
symptom_labels = {
    'NP2SPCH': 'Speech', 'NP2SALV': 'Saliva/Drooling', 'NP2SWAL': 'Swallowing',
    'NP2EAT': 'Eating', 'NP2DRES': 'Dressing', 'NP2HYGN': 'Hygiene',
    'NP2HWRT': 'Handwriting', 'NP2HOBB': 'Hobbies', 'NP2TURN': 'Turning',
    'NP2TRMR': 'Tremor', 'NP2RISE': 'Getting Up', 'NP2WALK': 'Walking',
    'NP2FREZ': 'Freezing'
}
symptom_df['Symptom'] = symptom_df['Symptom_Code'].map(symptom_labels)

# Calculate mean severity per symptom per stage
plot_data = (
    symptom_df
    .groupby(['Symptom', 'Combined_Stage'])['Severity']
    .mean()
    .reset_index()
)

# Order stages
stage_order = ['Early', 'Mid', 'Late']

# Plot
plt.figure(figsize=(12, 8))
sns.lineplot(
    data=plot_data,
    x='Combined_Stage',
    y='Severity',
    hue='Symptom',
    hue_order=sorted(symptom_labels.values()),
    style='Symptom',
    markers=True,
    dashes=False,
    estimator=None,
    sort=False
)
plt.title('Motor Symptom Severity Progression Across Stages', fontsize=14, fontweight='bold')
plt.xlabel('Disease Stage', fontsize=12)
plt.ylabel('Mean Severity Score', fontsize=12)
plt.xticks(ticks=range(len(stage_order)), labels=stage_order)
plt.legend(title='Symptom', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show()

import os
df1['EVENT_ID'] = df1['EVENT_ID'].astype(str)
df1.to_parquet('motor.parquet', engine='pyarrow', index=False)

